### ISSUE TITLE
boto3 sns publish to topic seems to not work as intended

### ISSUE THREAD

**Issue by nfons** [spulec/moto#1041]
We have a hard coded SNS topic we send data to, and need to unit test that functionality (in essence, when an error occurs we send an sns notification)

looking at the code here:
https://github.com/spulec/moto/blob/master/tests/test_sns/test_publishing_boto3.py#L15-L27
found from reply in this issue: https://github.com/spulec/moto/issues/979

now i see in code the topic_arn is gotten on the fly....is there anyway to test via hard coding...since our functionality is not creating the topic, but publishing to an existing topic.

my code looks a bit like this:
```
    def test_calls_sns_on_bad_type(self):
        moto = mock_sns()
        moto.start()
        conn = boto3.client('sns', region_name='us-east-1')
        conn.create_topic(Name='TOPIC-STUFF')
        cftClass = cftTemplateParser(CFT, 'path/to/BAD_FILE')
        fileType = cftClass.getFileType()
        self.assertRaises('File type is incorrect')
        moto.stop()
```

inside my actual code, the boto3 publish is hard coded:
`snsClient.publish('hard coded topic arn] :TOPIC-STUFF', message='blajh', Subject="subject")`

in console i am getting error:
raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFound) when calling the Publish operation: Endpoint with [hard coded topic arn] :TOPIC-STUFF not found

what would the best way to test these functionality?

**Comment by toshitanian** [comment]
master is updated, and link to lines seems to be incorrect. this is the link for tag 1.0.1 : https://github.com/spulec/moto/blob/1.0.1/tests/test_sns/test_publishing_boto3.py#L15-L27

**Comment by terrycain** [comment]
Is this still an issue?

**Comment by thrgamon** [comment]
I believe what @lilnate22 (and subsequently myself) were looking for was the following.

If you want to test a SNS service that publishes to a topic ARN stored as an environment variable (or hard coded), rather than a topic ARN generated dynamically, they seemingly always follow the pattern shown here:

https://github.com/spulec/moto/blob/b855fee2e4109eab04a9d55699ffeffb1ca51df6/tests/test_sns/test_topics_boto3.py#L21-L24

Therefore, if you know the topic name and region, you can encode the value as a environment variable. For example:

`SNS_ARN="arn:aws:sns:ap-southeast-2:123456789012:test_topic_for_testing"`

Hope this saves someone the few hours of searching that I had to do!

**Comment by bblommers** [comment]
I'm going to close this, as the last reply already points to the solution.

In general, when your code expects a specific resource to exist in AWS, the solution is always to generate this resource in your test setup before starting the actual test.
