### ISSUE TITLE
Sending SMS via SNS is not mocked; ARN is required

### ISSUE THREAD

**Issue by gavinmh** [spulec/moto#1189]
```
$ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moto
>>> moto.__version__
'1.0.1'
```

Example:
```
import boto3
from moto import mock_sns

mock = mock_sns()
mock.start()
client = boto3.client("sns")
client.publish(PhoneNumber="+15551234567", Message="my message")
```

Expected:
Return a dictionary per http://boto3.readthedocs.io/en/latest/reference/services/sns.html#SNS.Client.publish

Actual:
```
Traceback (most recent call last):
  File "/home/gavin/backend/notifications/tmp.py", line 7, in <module>
    client.publish(PhoneNumber="+15551234567", Message="my message")
  File "/home/gavin/backend/notifications/venv/lib/python3.5/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/gavin/backend/notifications/venv/lib/python3.5/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFound) when calling the Publish operation: Endpoint with arn None not found
```

**Comment by terrycain** [comment]
Will look into it

**Comment by terrycain** [comment]
@JackDanger can I get permissions to tag issues, have confirmed this is a bug.

Have found the offending code. As publishing with SNS matters, will need to add the ability to look up phone numbers linked to topics, get the topic arn then we'll be good.
```python
   def publish(self):
        target_arn = self._get_param('TargetArn')
        topic_arn = self._get_param('TopicArn')
        arn = target_arn if target_arn else topic_arn
        message = self._get_param('Message')
        message_id = self.backend.publish(arn, message)
```

**Comment by JackDanger** [comment]
@terrycain Sadly, that's not something I have the ability to give. @spulec could, though

**Comment by terrycain** [comment]
@spulec ^^ :wink:

**Comment by noah10** [comment]
I'm probably missing something, but why was the fix is to look up a topic arn? SNS allows publishing SMS messages straight to a phone number without any topic arn involved; [the docs](http://docs.aws.amazon.com/sns/latest/api/API_Publish.html) specify that you must provide either a phone number OR a topic arn OR a target arn but don't (as far as I can see) say that you need to provide more than one of those things. Am I missing something, or would it be possible for moto to support mocked SMS with no arn involved? I can probably add something to my test code to create the subscription, but it would be nice if I could avoid that.

**Comment by spulec** [comment]
Feel free to open an issue as a feature request and I will tag appropriately.
