### ISSUE TITLE
Question about NotImplementedError errors

### ISSUE THREAD

**Issue by josenrihernand** [spulec/moto#1223]
Hello everyone,

It is only to ask you a simple technical question.

According the following error messages I am getting using moto library, it looks like 
list_attached_group_policies (iam) and get_policy (iam) are not implemented yet.

NotImplementedError: The list_attached_group_policies action has not been implemented
NotImplementedError: The get_policy action has not been implemented

Could you please confirm if it is true ?

In have installed moto using:  "pip install moto" and next "pip install moto --upgrade".

Version of the products / language i am working with:
coverage --version
Coverage.py, version 4.4.1 with C extension

python --version
Python 2.7.5

boto3

virtualenv --version
15.1.0

Thank you very much in advance and, also, for your great contribution to the python community !   
Jose  :-)

**Comment by josenrihernand** [comment]
Sorry, in my previous question:

Instead of:
"In have installed moto using"

it should be:
"I have installed moto using"

thanks
Jose

**Comment by JackDanger** [comment]
@josenrihernand You're right that those aren't implemented yet. I've fixed that just now here: #1224 If you could give me a review of that code and approve it I'll merge it as soon as the tests pass!

**Comment by josenrihernand** [comment]
@JackDanger, I just saw your reply.  Thanks for fixing it so quickly!

I saw that the changes were merged. So, I upgrade moto on my box:  (pip install moto --upgrade).
NotImplementedError: The list_attached_group_policies action has not been implemented

After execute a new test, i no longer see the issue:
------------------------------------------------------------------
def get_group_policies(iam_instance, groups):

    """ Function to get the group policies """
    groupPolicies = iam_instance.list_attached_group_policies(
    GroupName = groups["GroupName"]
    );
    return groupPolicies;

groupPolicies = get_group_policies(iam_instance,groups);
print("Attached Group Policies: ", groupPolicies)

--> Now iam_instance.list_attached_group_policies works!
------------------------------------------------------------------

i'll continue working on other tests with moto... for example: get_policy (iam). I'll let you know the results..

Thanks a lot!
Jose

**Comment by josenrihernand** [comment]
Hello @JackDanger:

As for a recent test using get_policy (IAM) with moto library, i got a similar error:

policy = iam_client.get_policy(
            PolicyArn = attachedPolicy["PolicyArn"]
 );

NotImplementedError: The get_policy action has not been implemented

So, it seems that get_policy has not been implemented either.

In accordance to the current mock out script using moto, it'd be the only one method i need to execute, in order to pass all of my tests.

Thanks a lot !
Jose

**Comment by JackDanger** [comment]
@josenrihernand Much of the code in Moto is there because someone just like you found themselves in a similar problem and tried to add the missing endpoint. I'm not sure when I or another person will have time to implement `get_policy` but if you'd like to try you might find it's easier than you think.

What you'll need to do is three things:
* Add a `def get_policy(self):` method to the iam/responses file here: https://github.com/spulec/moto/blob/master/moto/iam/responses.py
* Add any appropriate methods you may need to retrieve the policy (though I believe this part may already be done) to the iam/models file here: https://github.com/spulec/moto/blob/master/moto/iam/responses.py
* Add at least one line to the tests that calls `get_policy` and makes sure the response is what you'd expect. That change should happen here: https://github.com/spulec/moto/blob/master/tests/test_iam/test_iam.py

If you do that then nobody will see that message in Moto anymore and it'll just work! If you'd like to try this please just start however you like and when you get stuck open a pull request and ask for help - there are a few folks who have a minute to help.

**Comment by josenrihernand** [comment]
@JackDanger:  Ok, thanks for the guidelines to implement it. 
Sure, i'll try, and when i have a stable version of this new method, i'll do a PR.

thank you very much!
