### ISSUE TITLE
Instance created by Autoscaling does not have subnet

### ISSUE THREAD

**Issue by mishraawake** [spulec/moto#1288]
When we create instance through autoscaling, the subnet of instance is not specified, It should be derived by autoscaling property "VPCZoneIdentifier"

**Comment by captainkerk** [comment]
Yeah, looks like we do ignore that parameter when launching new instances. Also, it looks like I've mistakenly set VPCZoneIdentifier to a VPC's ID, rather than a subnet in a few tests.

I'll try to fix this in the next few days.

**Comment by captainkerk** [comment]
Sorry about the delay, I have an update:

Turns out the actual autoscaling spec requires either Availability Zones or VPC Zone Identifier or both to be specified on ASG create, which we do not enforce.

The ideal way to fix this would be to enforce that requirement, rather than just tacking on creating an instance with a subnet if specified. It's been a bit more complicated to tack that on, and most of our tests don't create groups with AZs or VPC Zone Identifiers. 

I'll have a pull request soon.

**Comment by captainkerk** [comment]
Sorry @spulec, can you re-open this issue? I haven't quite fixed it, #1413 was just the first part. I'll have another PR with the remaining changes shortly.

**Comment by spulec** [comment]
Ah, got it. Thanks

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/1985
