### ISSUE TITLE
dynamodb update item with nested item issue

### ISSUE THREAD

**Issue by sunilkumarmohanty** [spulec/moto#1342]
Hi,

When I update_item with Update expression as 
SET #name1.#name2 = :value'
where name1 is a map

When I scan and read the item, I get the result as
'Name1.Name2':
the item is saved as #name1.#name2 instead of a map structure. Is it a known issue

**Comment by terrycain** [comment]
Not a known issue as far as im aware, can you create a simple test case for this and i'll look into it

**Comment by VitalyIvanov** [comment]
I have the same issue. It seems UpdateExpression doesn't work with Nested Map Attributes properly. I'm using mock_dynamodb2.

If I run something like this
```python
table.update_item(
            Key={
                'ID': id,
            },
            UpdateExpression='SET ResultMap.#final.#key = :status',
            ExpressionAttributeNames={
                '#final': 'Final',
                '#key': 'Key'
            },
            ExpressionAttributeValues={
                ':status': 'status'
            }
        )
```
and then read the data with scan, a result item contains a new attribute with the key 'ResultResources.Final.Key' instead of updating a nested attribute. It works properly if I run my function on AWS.

**Comment by terrycain** [comment]
Should fix it. No garuentees but it fixes @VitalyIvanov's example

**Comment by VitalyIvanov** [comment]
@terrycain Great! Thank you! My use case now works just fine.

**Comment by terrycain** [comment]
No problem mate. Glad its working, that bit of the code is proper evil :D
