### ISSUE TITLE
no error or warning when creating s3 bucket that already exists in standalone server

### ISSUE THREAD

**Issue by dtenenba** [spulec/moto#1371]
Python 3.6.3
boto3==1.4.8
moto==1.1.25

I know I should be using the decorators and not the standalone server, but this still seems like a bug. After starting the standalone server: 

```
moto_server s3
```

I run this code:

```python
import boto3
boto3.setup_default_session()
s3 = boto3.client(service_name="s3", region_name="us-west-2", endpoint_url="http://localhost:5000")
result = s3.create_bucket(Bucket='mybucket')
print(result)
result = s3.create_bucket(Bucket='mybucket')
print(result)
```
I expect that last line to return a stack trace with the message `BucketAlreadyOwnedByYou: An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.` That's what I get in actual S3 when trying to create a bucket I have already created.

But instead it succeeds without comment just like the first call to `create_bucket`.

This is what it outputs:

```
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/html; charset=utf-8', 'content-length': '174', 'server': 'Werkzeug/0.12.2 Python/3.6.3', 'date': 'Mon, 04 Dec 2017 04:24:04 GMT'}, 'RetryAttempts': 0}}
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'text/html; charset=utf-8', 'content-length': '174', 'server': 'Werkzeug/0.12.2 Python/3.6.3', 'date': 'Mon, 04 Dec 2017 04:24:04 GMT'}, 'RetryAttempts': 0}}
```

If I upload a file to the bucket after the first bucket creation, that file is still there after the second creation. So it's not overwriting the original bucket, it's just not telling me that bucket already exists.

I'm trying to test code that relies on the correct behavior, so...

**Comment by dtenenba** [comment]
FWIW this happens with the decorator as well:

```python
"test harness"
from moto import mock_s3
import boto3

@mock_s3
def testit():
    "testit!"
    boto3.setup_default_session()
    s3 = boto3.client(service_name="s3", region_name="us-west-2")
    result = s3.create_bucket(Bucket='mybucket')
    print(result)
    result = s3.create_bucket(Bucket='mybucket')
    print(result)

if __name__ == '__main__':
    testit()

```

Output:

```
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'Content-Type': 'text/plain'}, 'RetryAttempts': 0}}
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'Content-Type': 'text/plain'}, 'RetryAttempts': 0}}
```

**Comment by c3st7n** [comment]
https://github.com/spulec/moto/issues/273 - added a special behaviour to mimic the actual behaviour of AWS.

Creating a bucket in us-east-1 will actually succeed and return the original bucket in that region only.

Now the thing this is also more confusing because setting the region_name on the S3 client doesn't change the region that the bucket it is created in, so we are defaulting to us-east-1 which has this behaviour.

 If you set a bucket location constraint to a non us-east-1 region on the dupe create bucket requests then the exception is raised as expected. I have done a few tests and the behaviour is pretty much the same as boto3 for real, except for the following case:
* if you create the s3 client in a region (for example eu-west-1) then called create-bucket without a location constraint to the same region, then it will raise an IllegalConstraintException (The unspecified location constraint is incompatible for the region specific endpoint this request was sent to).

So this isn't a moto bug just very odd corner case behaviour for the actual S3 service in us-east-1.
