### ISSUE TITLE
[discussion] ECS + Lambda

### ISSUE THREAD

**Issue by thehesiod** [spulec/moto#1388]
After reporting https://github.com/spulec/moto/issues/1386, I talked to another dev and his first question was how is that a mock? Annnd, then a huge mental rift opened when I realized we took a similar route with Lambda...so I guess the question is, is moto really moto, or is it more of a https://github.com/localstack/localstack?  What should be the goals?  moto never really seemed like a true mocking library because it didn't really want you fine-tuning responses.

On one hand I think if we were to implement ECS a lot more tests could be unlocked, on the other hand being able to fine-tune the responses would be nice too.

_floodgates opened_ =)

**Comment by terrycain** [comment]
Haha, I even considered the other day to adapt the route53 part to actually serve DNS. Well the dynamo part is getting to be near enough a fully fledged python dynamodb implementation, on the other hand Batch uses Docker too (although image is hardcoded atm).

I think if we wanted fine tuning, we'd need to make an api sorta thing for moto so that test cases can customise things (I thought about adding in some json to botocore to add a moto aws service a while back just for kicks). I see no reason why moto couldnt do both but fine-tuning would take more work that a localstack I think

**Comment by spulec** [comment]
I don't have a great answer here, but it seems like it will vary service by service.

Implementing lambda seems reasonable-ish to me. Implementing a fake dynamodb that doesn't actually give the scalability of real dynamodb is good. If we find ourselves implementing a fake mysql for RDS, then we have gone too far.

I don't have a better answer than that. I think we will need to discuss each one as they come. I'm going to close this for now, but happy to discuss more if helpful.
