### ISSUE TITLE
Dynamodb2 update_item operation does not always return the UPDATED_OLD attributes.

### ISSUE THREAD

**Issue by hsq125** [spulec/moto#2860]
# Expected behaviour

The `update_item` operation can return the item attributes as they appear before or after they are updated, depending on the `ReturnValues` parameter.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html

When set to `UPDATED_OLD` it should  
> Returns only the updated attributes, as they appeared before the UpdateItem operation.

# Problem

When updating an item once (incrementing an attribute used as counter for exemple), the value of the updated attributes is correclty returned. Great.

But when updating the same item a second time in a row, the value is no longer returned at all. 

A minimal test for reproducing the issue is attached to the ticket (it is .txt file altougth it should have been .py; but it is not accepted by github).

[moto_dynamodb_update_return_old_failure.txt](https://github.com/spulec/moto/files/4423741/moto_dynamodb_update_return_old_failure.txt)

# Environment

Python 3.7.5

moto (1.3.14)
boto (2.49.0)
boto3 (1.11.13)
botocore (1.14.13)

moto was installed well after boto*, with `pip install moto`

# Thanks
Because there is no other place to say otherwise : thanks a lot for this great lib. I love it !!

**Comment by bblommers** [comment]
Hi @hsq125, it looks like the underlying problem is simply that the UpdateExpression that you're using is not yet supported by moto.
The value is always set as ```v + :inc```, instead of computing the desired value. So when you run that same UpdateExpression, the value is updated from ```v + :inc``` to ```v + :inc``` - i.e., it never changes.

The moment the UpdateExpression is properly evaluated, the ReturnValues-attribute behaves correctly.

I've proposed a PR to support the ```set x = x + 1``` expression, and added your test case to verify that your issue is fixed at the same time
