### ISSUE TITLE
State tracking

### ISSUE THREAD

**Issue by mdaif** [spulec/moto#3600]
Hi !
Thanks for the great effort ! This is a very neat piece of software ! :-)
One question though, how does Moto persist the state ? I've noticed that even if the test finishes the old objects (in S3 in this case) persists and I've to remove them manually.
Thanks a lot !

**Comment by bblommers** [comment]
Hi @mdaif, good to hear Moto is useful!
State is always stored in memory. This is always reset after every decorator finishes, so it should not persist in between tests.

Can you share an example where you're seeing this?

**Comment by mdaif** [comment]
Hi @bblommers. Thanks for your reply. Let's close this issue, it was a bug on my side :))

**Comment by sumanthkumarc** [comment]
Is there a way to persist mock data beyond the decorator execution? like say i'm writing multiple tests for say iam user resource, i need to re-create user resource again and again in each function??

**Comment by bblommers** [comment]
Hi @sumanthkumarc, not at the moment. The easiest way to recreate resources would be to use a fixture and autocreate it for every test.
Alternatively, you can use a class-based decorator:
```
import unittest
import moto
import boto3


@moto.mock_iam
class TestMyClass(unittest.TestCase):

    client = None

    def setUp(self) -> None:
        self.client = boto3.client('iam')
        self.client.create_user_once()

    def test_something(self):
        pass
        # user will already be created here
```
Keep in mind that that might have unintended consequences - resources created in `test_something` will also be available in other tests within this class.

**Comment by sumanthkumarc** [comment]
Thanks @bblommers for super quick reply. Appreciate it. 

I actually did try using fixtures but the resources doesn't seem to persist because as per your comment above: `This is always reset after every decorator finishes`, So once the code comes out of fixture the resources are gone. Yes i discovered myself that class might be better way to do this.

That said i think if moto had similar scope param like pytest - function, package, module etc, that would be awesome.
