### ISSUE TITLE
Unable to request for a presigned URL

### ISSUE THREAD

**Issue by amarjandu** [spulec/moto#3790]
I am unable to perform a GET request on a presigned URL for a file that has been uploaded.
I've attached a reproduction here: https://gist.github.com/amarjandu/77a7d8e33623bae1e4e5ba40dc043cb9
The py file that was executed in the reproduction is attached within the gist as well.

My expectation is that the file should be accessible from the presigned URL, this functionality was working on 1.3.13
https://gist.github.com/amarjandu/fb4454e90924d3814772eca68d10dace

This seems like it has to do with the `self._matches` attribute that is used around the `_find_match` functionality in `moto/core/models.py` def https://github.com/spulec/moto/blob/74272ae51cd26397c5f8453ea85a5aeb09f40cdb/moto/core/models.py#L279

The ordering of the object when its enumerated looks off, the CallbackResponse that should be returned is not the first match that is found, its one of the `The method is not implemented` responses, seems like these should only be used as a last resort.

<img width="1786" alt="Screen Shot 2021-03-19 at 1 51 16 PM" src="https://user-images.githubusercontent.com/1947534/111840775-2f12fc00-88ba-11eb-8d85-11887eaa12f6.png">

Moto Version: 
```
(.venv) CBSEspecter:azul amar$ pip list | grep oto
boto3              1.17.33
botocore           1.20.33
moto               2.0.2
```
I started a clean virtualenv and ran `pip install moto[all]==2.0.2`

**Comment by amarjandu** [comment]
Here is a more simple reproduction that also fails on `moto 2.0.2`.

https://gist.github.com/amarjandu/631d741ffa5c554d8a4398843ba54fc3

**Comment by bblommers** [comment]
Hey @amarjandu, thanks for raising this! Looks like you're right on point with your analysis.

This is the list of callbacks for your example:
`[<function not_implemented_callback at ...>, <moto.core.utils.convert_flask_to_responses_response object at ...>, <function not_implemented_callback at ...>]`

The `not_implemented_callback` is added twice, once by the `mock_sts` and once by the `mock_s3` decorator.
Because of the ordering, the `mock_sts`-decorator is processed first, so the `not_implemented_callback` is added to the list first. 

As a workaround, you can switch the decorators:
```
@moto.mock_s3
@moto.mock_sts
def bar(self):
```
Which would result in this list of callbacks:
`[<moto.core.utils.convert_flask_to_responses_response object at ...>, <function not_implemented_callback at ...>, <function not_implemented_callback at ...>]`

Will submit a PR with a fix shortly.

**Comment by amarjandu** [comment]
@lucaghera
Moving the discussion from here: https://gist.github.com/amarjandu/77a7d8e33623bae1e4e5ba40dc043cb9#gistcomment-3715160

Yeah changing the ordering as @bblommers had recommend resolved the issue for us.

**Comment by lucaghera** [comment]
Thanks for the input, it seems that also in my case reordering moving `mock_s3` first helps. In my test I do not use `sts`, but I have `mock_dynamodb`, `mock_cognitoidp`, and `mock_dynamodb2`.

I'm not an expert of this, but should I be expected of finding the right order or is this something that the bug fix will address for the all the services?

Also, out of curiosity. Why do other services generate a match for a request of an S3 feature?

Thanks again!

**Comment by bblommers** [comment]
> I'm not an expert of this, but should I be expected of finding the right order or is this something that the bug fix will address for the all the services?

The bugfix will address this for all services, so that the order never matters


> Why do other services generate a match for a request of an S3 feature?

Moto only intercepts the HTTP requests that are made by boto3, but by the time we intercept the HTTP request it's not obvious anymore from which service it came from originally.
So when the decorators start, it creates a list of all possible HTTP request matches. When any request comes in, it will iterate through all of them to see which one matches - regardless of the service it belongs to.

**Comment by lucaghera** [comment]
Thanks @bblommers for your answer, very clear!
