### ISSUE TITLE
Archive Event Pattern issues/enhancements

### ISSUE THREAD

**Issue by gruebel** [spulec/moto#3837]
Seeing the enhancement from @TSNoble regarding EventBridge Archive Pattern, I think I should offer my personal experience here, because I initially implemented it. I think it was a great idea to create a dedicated `EventPattern` class, I also taught about it, but had no time to work on it.

So, how it was implemented is actually not correct at the moment. The Archive Event Pattern has no real meaning, because EventBridge puts everything into a self managed Event Rule `Events-Archive-[name of archive]` there it merges the provided Archive Event Pattern with a special pattern to not archive it's own messages again, when a replay was initiated.
```
{
  "replay-name": [{
    "exists": false
  }]
}
```

That was the reason why I created
https://github.com/spulec/moto/blob/b138d9956bf784a122b31508e27c71c71b9d0483/moto/events/models.py#L103
so there is no special magic for Archive Event Patterns, they are all normal Event Rule Patterns. So, it would be great to move everything there, then also the normal rules can benefit from the new functionality

An other issue is the recent integration of the `exists` filter, it will be only applied on the leaves of the tree not on the branches. This test should pass and not fail
```
bar_not_exists = EventPattern(json.dumps({"detail": {"bar": [{"exists": False}]}}))
assert bar_not_exists.matches_event({"detail": {"bar": {"foo": "bar"}}})
```
https://docs.amazonaws.cn/en_us/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html#eb-filtering-exists-matching

**Comment by TSNoble** [comment]
Hey @gruebel. Thanks for the information and suggestions. I'll try to raise a PR soon moving the validation logic into the EventPattern class and extending its use to all Rules, rather than just for Archives.

I think the `exists` logic is correct, as in the example you've given "bar" is the value of field "foo", rather than a field itself, though admittedly the documentation is a little ambiguous (is a leaf node a field with no sub-fields, or the _value_ of such a field)? I interpreted it the former way but will check how boto handles it and include a change if there's differing behaviour
