### ISSUE TITLE
Change state to `active` when describing load balancer

### ISSUE THREAD

**Issue by giovtorres** [spulec/moto#3936]
Would there be any objection to changing the `State` of a newly created load balancer to `active` instead of `provisioning`?

https://github.com/spulec/moto/blob/d3f20694a90209d1dd39f27e528edfa7d170d429/moto/elbv2/responses.py#L708-L710

The use case would be that if application code waits for the load balancer state to transition from `provisioning` to `active` before taking further actions.

**Comment by bblommers** [comment]
Hi @giovtorres,  returning 'provisioning' in the `create_load_balancer`-call would be the appropriate AWS response.

Am I correct in assuming that you use the `describe_load_balancers`-call (or one of the waiters) to check when the state is 'active'?
Because changing the response of `describe_load_balancers` to say 'active' would make a lot of sense, and that keeps in line with the AWS behaviour.

In other services we sometimes have a counter, where a state will only advance (from 'provisioning' -> 'active') after a certain number of calls, to mimick the asynchronicity that will occur in real live. I don't have enough knowledge of ELB to say whether an artificial wait time like that would make sense, though

**Comment by giovtorres** [comment]
> Am I correct in assuming that you use the `describe_load_balancers`-call (or one of the waiters) to check when the state is 'active'?
> Because changing the response of `describe_load_balancers` to say 'active' would make a lot of sense, and that keeps in line with the AWS behaviour.

Yes, I would use `describe_load_balancers` to check when the state is `active`.

> In other services we sometimes have a counter, where a state will only advance (from 'provisioning' -> 'active') after a certain number of calls, to mimick the asynchronicity that will occur in real live. I don't have enough knowledge of ELB to say whether such an artificial wait time would make sense here, though

Do you have an example in the code where there is a counter to change the state?


The ELBv2 API seems to have 4 states:  `provisioning`, `active`, `active_impaired`, and `failed`.

Would it make sense to allow the user to configure the end state of the load balancer in order to test against the different states? The state could always start with `provisioning` and then transition to the end state after a configurable number of calls? Or, it could be less complex and just transition to `active`.

Thoughts?

**Comment by bblommers** [comment]
I can't find an example with a counter atm, but a simple advance/transition can be done like this:
https://github.com/spulec/moto/blob/d3f20694a90209d1dd39f27e528edfa7d170d429/moto/support/models.py#L81-L101

A configurable endstate would be ideal, yes, which can be implemented with the user setting an environment variable. 
I imagine the less complex variant, `provisioning -> active`, would already be very useful for most users, so that can be a first iteration.
