### ISSUE TITLE
lambda requires IAM configuration

### ISSUE THREAD

**Issue by yuvalif** [spulec/moto#3944]
I've set:
```
export INITIAL_NO_AUTH_ACTION_COUNT=100
```
and then running moto server for testing lambdas:
```
moto_server lambda -p 5555
```

when trying to create a lambda function:
```
aws lambda --region=us-east-1 --endpoint-url=http://localhost:5555 create-function --function-name gsoc20 --zip-file fileb://file.zip --handler index.handler --runtime python --role arn:aws:iam::123456789012:role/lambda-ex
```
i get the following error:
```
An error occurred (400) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
```

Is it possible to define a lambda function without defining a role first?

**Comment by bblommers** [comment]
Hi @yuvalif!


> Is it possible to define a lambda function without defining a role first?

That's not possible, no. Moto implements some basic checks to verify that the role exists, mimicking the AWS behaviour around this feature.

Creating the role is possible, as long the moto_server is started without any service parameter:
```
moto_server -p 5555
```
This will start a server for every service, so that both IAM and AWSLambda can talk to the same endpoint.

The unmodified IAM call will now succeed:
```
aws iam --region=us-east-1 --endpoint-url=http://localhost:5555 create-role --role-name "lambda-ex" --assume-role-policy-document "some policy" --path "/my-path/"
```
The AWSLambda call needs a different `role-arn`-parameter, as the path is also part of the ARN:
```
aws lambda --region=us-east-1 --endpoint-url=http://localhost:5555 create-function --function-name gsoc20 --zip-file fileb://file.zip --handler index.handler --runtime python --role arn:aws:iam::123456789012:role/my-path/lambda-ex
```

**Comment by yuvalif** [comment]
@bblommers thank you for the reply!
This fixed the role and lambda creation issue.

**Comment by bblommers** [comment]
Happy to hear that! Will close this, but let us know if you run into any other issues.
