### ISSUE TITLE
Generate models and APIs using AWS Cloud Control?

### ISSUE THREAD

**Issue by lorengordon** [spulec/moto#4696]
I was curious if any thought had been given to generating models and APIs for moto using the AWS Cloud Control API? The idea came from the new terraform awscc provider, which is based on code generation from this new service... I realize that is Golang, but surely there must be some equivalent in Python?

* https://aws.amazon.com/blogs/aws/announcing-aws-cloud-control-api/
* https://github.com/hashicorp/terraform-provider-awscc
* https://learn.hashicorp.com/tutorials/terraform/aws-cloud-control
* https://www.hashicorp.com/blog/announcing-terraform-aws-cloud-control-provider-tech-preview

**Comment by bblommers** [comment]
Hey @lorengordon! I read the AWS accouncement, but didn't know that Terraform already has a module utilizing this API. From what I can tell, TF uses it to auto-generate CloudFormation templates, is that correct?

Moto needs to know the following in order to mock everything:

1. The input-format used in boto3 (i.e., which parameters are used in the boto3-client call)
2. The format of the HTTP-request send by boto3
3. The format and type of the HTTP-response expected by boto3
4. The internal logic of what to do with the input

At the moment, we're using a homegrown scaffolding script that deals with the first three, by parsing the botocore service-data. It's not perfect, and it doesn't reliably work for every service/feature, but I'm not sure how Cloud Control API could help us in this process.

**Comment by lorengordon** [comment]
My understanding is no, there are no CloudFormation templates or stacks involved! It is pure hcl + terraform lifecycle on the user side. I'm not yet sure whether terraform is interacting directly with per-service endpoints, or with an awscc endpoint. But basically the awscc provider retrieves the service model and then generates golang for every service and resource supported by AWS Cloud Control. For the user, it's all just hcl + terraform, with no CloudFormation anywhere.

The FAQ might help: https://github.com/hashicorp/terraform-provider-awscc/blob/main/contributing/FAQ.md

**Comment by bblommers** [comment]
Looks like the service model can be retrieved using `describe-type`:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/describe-type.html

It does seem like the service model is very CF-centric. So the exposed model can easily be transformed into HCL, but that does not necessarily correlate to the AWS HTTP request/response format that Moto needs.
