### ISSUE TITLE
Implement `db-cluster-id` filter for RDS DBInstanceAvailable waiter

### ISSUE THREAD

**Issue by mattBrzezinski** [spulec/moto#5091]
## Overview
* boto3 == 1.22.5
* botocore == 1.25.5
* moto == 3.1.7

When attempting the code below we get an error `FAILED tests/{REDACTED} - NotImplementedError: db-cluster-id filter has not been implemented in Moto yet.`

```python
rds_client.get_waiter("db_instance_available").wait(
    Filters=[{"Name": "db-cluster-id", "Values": [db_id]}]
)
```

The boto3 documentation for [RDS.Waiter.DBInstanceAvailable](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Waiter.DBInstanceAvailable) lists `db-cluster-id` as a valid filter.

**Comment by bblommers** [comment]
Hi @mattBrzezinski, welcome to Moto, and thanks for raising this! Will mark it as an enhancement to implement this filter.

**Comment by bblommers** [comment]
A PR would be very welcome, @mattBrzezinski! There is no similar PR, that I can find, but I may be able to point you in the right direction.
The first step would be to intercept the `DBClusterIdentifier`-parameter when creating a DB instance, because it doesn't look like that's in place yet.
https://github.com/spulec/moto/blob/147f52fedc4283dec24f291c83a2b9a54541d958/moto/rds/responses.py#L158

Second step: Ensure this attribute is pushed through all the way to the `rds.models.Database`-class

Third: Implement the actual FilterDef, to filter on the new field that contains the `DBClusterIdentifier`-value:
https://github.com/spulec/moto/blob/147f52fedc4283dec24f291c83a2b9a54541d958/moto/rds/models.py#L310

Fourth step would be to create a test for it - there are quite a few examples already that you can borrow from in `tests/test_rds/test_filters.py`.

And finally, a link to our general development guide that may come in handy:
http://docs.getmoto.org/en/latest/docs/contributing/index.html

Let me know if you have any other questions, happy to help out!
