### ISSUE TITLE
Support new, longer instance and reservation IDs

### ISSUE THREAD

**Issue by twexler** [spulec/moto#511]
Currently this is an opt-in, but will be required by the end of the year. I propose that this is just a boolean kwarg defaulting to true on the mock_\* functions that require it. Thoughts?

https://aws.amazon.com/ec2/faqs/#longer-ids

**Comment by spulec** [comment]
Thanks for opening!

I don't hate it, but am a bit worried about the amount of layers the boolean will need to travel, especially since we will undo all of the code at some point. I'm tempted to suggest reading an environment variable, but that feels hacky.

I don't have a strong preference either way. If someone wants to submit a PR, I will happily merge, but prefer they setup the code in a manner that will make it easy to remove at year end.

**Comment by twexler** [comment]
Thanks for the response @spulec, now that I've had more time to review the process in getting the longer instance IDs set up in the actual AWS API, I'm feeling like we should implement a "mock" of [`ModifyIDFormat`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyIdFormat.html) that persists the boolean somewhere. I'll dig into this more later this week!

**Comment by terrycain** [comment]
@JackDanger should be done, close please

**Comment by JackDanger** [comment]
@terrycain Many thanks for the help with issue triaging
