### ISSUE TITLE
Not all models with create_from_cloudformation_json can be updated or deleted through cloudformation

### ISSUE THREAD

**Issue by hltbra** [spulec/moto#793]
There should be a standard for create/update/delete methods on models that support CloudFormation.

The `Instance` model has only `create_from_cloudformation_json`, for example.

There is a method `delete_from_cloudformation_json` in many models, but that doesn't get called when a stack is deleted, it gets called when the stack is updated. When stacks are deleted, the instance method `delete` is called (if it exists). There's some inconsistency here.

**Comment by 2rs2ts** [comment]
Hiya, I'm partly responsible for this inconsistency.

The reason for this inconsistency is the fact that the `DeleteStack` API call does not take a template, so there is no way to call `delete_from_cloudformation_json`. You'll see how that plays out [in the implementation](https://github.com/spulec/moto/blob/e1260bca06b8ac4cf8ecf72b0f4d3234b166b2b6/moto/cloudformation/models.py#L169). Instead, we've shimmed in `delete` methods for the models that need to be able to be deleted from a `DeleteStack` call even if they don't have some delete method wired up to them initially.

For instance, this PR added functionality to resources that I was using, and nothing more (because I didn't need anything more.) #576 You'll notice that when I implemented `delete` on the models, I noted that the method wasn't exposed, but merely used for CloudFormation.

You should also remember that `delete_from_cloudformation_json` is a classmethod which figures out which model instance the template resource refers to, and tells the backend to delete it. The `delete` method is an instance method instead, so it's called when you're sifting through the resource map or when resources that are linked (for example, ASGs and Instances) need to delete their dependants when they themselves are deleted. Sometimes a backend will call the `delete` method.

So while there _are_ two methods to delete a resource, you can think of them as being different approaches you have to take depending on what information is available to you. As for why some models don't have implementations for the CloudFormation methods... well, it's just because no one has needed them yet, so no one went to the effort to implement them. ;)

Hopefully this might make you feel a little less uncomfortable about the code. Or even better, it'll help you think of ways to improve moto!

**Comment by bblommers** [comment]
Couple of years later.. there is a standard now! All implementations should extend the abstract `CloudFormationModel`-class, and implement `create_from_cloudformation_json`/`update_from_cloudformation_json`/`delete_from_cloudformation_json` as appropriate.
The `delete`-method on individual resources is still available, but `delete_from_cloudformation_json` is the preferred approach.


> 
> As for why some models don't have implementations for the CloudFormation methods... well, it's just because no one has needed them yet, so no one went to the effort to implement them. ;)
> 

This is very much still the case though - and I expect it will always be so. :slightly_smiling_face: 

I'll close this, but let us know if there are any other questions around this.
