### ISSUE TITLE
[Feedback Requested] Moto 1.0 Plan

### ISSUE THREAD

**Issue by spulec** [spulec/moto#848]
I've been doing some work on a major upgrade of Moto and would appreciate any feedback/testing.

Big changes:
  - [x] Deprecate HTTPretty and boto support. These will still exist for now, just with separate decorators (@mock_ec2_deprecated). Since HTTPretty mocks at the socket level, it has caused issues in the past. Since we will primarily be supporting boto3 (and server mode) in the future and boto3 uses requests, we are switching to [Responses](https://github.com/getsentry/responses)
  - [x] More focus more on standalone server mode. I want Moto to work with any programming language. I've gone through and ensured that all of the tests work in server-mode and configured that to run on Travis going forward. As the projects moves forward, I see server mode becoming the primary way to use Moto and providing a few helpers for various programming languages.
  - [x] Drop python 2.6
  - [ ] Moto APIs
    - In the past, I've been hesitant to start adding custom APIs to manipulate state. I'm coming around on it :)
    - [x] Reset API: I've added a reset API to flush all of the current data  `requests.post("http://motoapi.amazonaws.com/moto-api/reset")`.
    - [ ] Exceptions: I'm looking to add a similar endpoint to force Moto to [raise exceptions](https://github.com/spulec/moto/issues/722). Maybe `requests.post("http://motoapi.amazonaws.com/moto-api/set-next-error", data={"status_code": 400, "body": "Throttling Error: too many requests"})`. The subsequent request would then return a 400 response with the designated response body. I would like a better way than this, but can't think of anything.
  - [x] Dashboard: A very basic dashboard to be able to see the current state of the system would be nice (list instances, queues, etc).

Feedback welcome.

The deprecation of HTTPretty and cleanup of the server mode is already available on [a branch](https://github.com/spulec/moto/tree/deprecate-httpretty). If anyone is able to give that branch a test and report any issues, it would be very much appreciated.

**Comment by stujfiter** [comment]
I think the push toward stand alone server mode is a good move.  Also, a dashboard would be very helpful and save me from trying to query the moto virtual env for state.

**Comment by bkruger99** [comment]
Will decorators in general still be a part of the redesign even without HTTPretty?  Or will those be going away in general.. FWIW, I've been using responses and been quite happy with it with other unit testing.

**Comment by spulec** [comment]
Yes, decorators will still remain (just based on Responses). Although we will push toward server-only mode, I imagine we will always have some type of easy support for python.

**Comment by gjtempleton** [comment]
This seems like the most sensible way forward to me in all respects. 

Boto is beginning to fall further and further behind features wise (certainly in terms of ECS, my current major focus), but more importantly I think a move to the standalone server model, allowing users to be language agnostic makes a huge amount of sense. Allows for consistent testing strategies across different languages.

**Comment by JackDanger** [comment]
I appreciate all of the work you've done so far and this seems like a great path forward. I was slow to agree about focusing on server mode but now I think it'll bring in many more developers and make this project easier to develop on and use for everybody. A decorator-based Python client wouldn't be too hard to build for a purely server-mode Moto, either.

The `set-next-exception` endpoint feels like the kind of thing that'll be welcomed at first and reverted 8 months later because the abstraction is a bit leaky. We'd have to set the expectation on the inbound connection to support concurrency and that would definitely surprise developers who either don't know their concurrency model or don't know when their code creates new connections.

I'd prefer some Moto-specific header like `X-Moto-Expects: ConstraintViolationError` in the request which would then make implementing specific error responses very easy and make the documentation for using them quite simple.

@spulec, I can't thank you enough for your work on this. It's a truly marvelous project.

**Comment by spulec** [comment]
As of now, there will be no plans to completely eliminate a Python decorator from Moto (it is still how I use Moto).

I agree that a header-based approach to exceptions sounds much better. Thanks!

**Comment by georgepsarakis** [comment]
@spulec great! Using the decorators for mocking in tests is definitely essential as it allows to not interfere with boto3 client initialization using parameterized endpoint URLs.

**Comment by spulec** [comment]
Since version `1.0.0` was released, I'm going to close this. Please open issues for any feedback on the release or other feature ideas.
